### ISSUE TITLE
Create tags for versions

### ISSUE THREAD

**Issue by vovkab** [flurry/FlurryAdapterForMoPubAndroid#8]
Looks like right now tags is missing completely, and you can only guess which version is where.

**Comment by ugonna** [comment]
If using MoPub pre-4.0.0 or Flurry SDK pre-6.0.0, there is [a tag](https://github.com/flurry/android-FlurryAdapterForMoPub/tree/v5.4.0_for_mopub_pre_4.0.0) of the adapter that supports that version. Otherwise, the latest version of the adapter should work with all versions of MoPub 4+ and all new versions of the Flurry SDK, regardless of point release.

More version tags will be added in the future, especially for breaking changes.
